services:
  edmil.communication.db:
    container_name: communicationdb
    hostname: communicationdb
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=communicationdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: # Persistent storage for Postgres
